[package]
name = "bonjour-sys"
version = "0.1.0"
authors = ["Walker Crouse <Walker.Crouse@bjss.com>"]
edition = "2018"
build = "build.rs"

[build-dependencies]
bindgen = "0.54.1"

[dependencies]
libc = "*"
